/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BasicPensionAmount = {
  fromDate?: string;
  amount?: number;
};

export type EmployeeBudget = {
  title?: string;
  subTitle?: string;
  epolyeeBudgetsPosts?: Array<
    {
      _key: string;
    } & EmployeeBudgetPost
  >;
};

export type Benefits = {
  title?: string;
  subTitle?: string;
  benefitItems?: Array<
    {
      _key: string;
    } & BenefitItem
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Illustration = {
  _type: 'illustration';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type Container = {
  _type: 'container';
  content?: Array<
    | ({
        _key: string;
      } & CallToAction)
    | ({
        _key: string;
      } & ListSection)
    | ({
        _key: string;
      } & TextSection)
    | ({
        _key: string;
      } & Paragraph)
    | ({
        _key: string;
      } & Illustration)
  >;
  fullWidth?: boolean;
  background?: string;
};

export type TextSection = {
  _type: 'textSection';
  heading?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Paragraph = {
  _type: 'paragraph';
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type ListSection = {
  _type: 'listSection';
  heading?: string;
  list?: Array<string>;
};

export type Hero = {
  _type: 'hero';
  heading?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  callToAction?: CallToAction;
};

export type CallToAction = {
  _type: 'callToAction';
  linkText?: string;
  url?: string;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<
    | ({
        _key: string;
      } & Container)
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & CallToAction)
    | ({
        _key: string;
      } & ListSection)
    | ({
        _key: string;
      } & TextSection)
    | ({
        _key: string;
      } & Paragraph)
    | ({
        _key: string;
      } & Illustration)
    | ({
        _key: string;
      } & Calculator)
    | ({
        _key: string;
      } & Contact)
  >;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SectionLabelReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'section-label';
};

export type ManualSection = {
  _id: string;
  _type: 'manual-section';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  label?: SectionLabelReference;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  slug?: Slug;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SectionLabel = {
  _id: string;
  _type: 'section-label';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
};

export type ManualSectionReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'manual-section';
};

export type StaffManual = {
  _id: string;
  _type: 'staff-manual';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  sections?: Array<
    {
      _key: string;
    } & ManualSectionReference
  >;
};

export type JobDescription = {
  _id: string;
  _type: 'job-description';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  label?: string;
  subtitle?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  description?: {
    en?: string;
    no?: string;
  };
  extraDescription?: string;
  showOnFrontPage?: boolean;
  content?: Array<
    | {
        text?: string;
        _type: 'heading';
        _key: string;
      }
    | {
        text?: string;
        _type: 'paragraph';
        _key: string;
      }
    | {
        text?: string;
        _type: 'output';
        _key: string;
      }
    | {
        text?: string;
        author?: string;
        _type: 'quote';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'wideimage';
        _key: string;
      }
  >;
  technologies?: Array<string>;
};

export type Social = {
  _id: string;
  _type: 'social';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: string;
  url?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type People = {
  _id: string;
  _type: 'people';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  socials?: Array<{
    type?: string;
    url?: string;
    _type: 'social';
    _key: string;
  }>;
};

export type BenefitItem = {
  _type: 'benefitItem';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  title?: string;
  text?: string;
  amountYearly?: number;
  fixedBenefits?: boolean;
};

export type EmployeeBudgetPost = {
  _type: 'employeeBudgetPost';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  title?: string;
  amountYearly?: number;
  amountTotal?: number;
  fixedBenefits?: boolean;
};

export type Calculator = {
  _type: 'calculator';
  title?: string;
  basicPensionAmount?: BasicPensionAmount;
  yearlyPensionSaving?: number;
  estimatedSalaryIncrease?: number;
  employeeBudget?: EmployeeBudget;
  benefits?: Benefits;
  salaryStpes?: Array<number>;
};

export type ContactInfo = {
  _type: 'contactInfo';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  name?: string;
  phone?: number;
  jobTitle?: string;
  email?: string;
};

export type Contact = {
  _type: 'contact';
  title?: string;
  subText?: string;
  contactInfos?: Array<
    {
      _key: string;
    } & ContactInfo
  >;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BasicPensionAmount
  | EmployeeBudget
  | Benefits
  | SanityImageAssetReference
  | Illustration
  | Container
  | TextSection
  | Paragraph
  | ListSection
  | Hero
  | CallToAction
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SectionLabelReference
  | ManualSection
  | Slug
  | SectionLabel
  | ManualSectionReference
  | StaffManual
  | JobDescription
  | Project
  | Social
  | ProjectReference
  | People
  | BenefitItem
  | EmployeeBudgetPost
  | Calculator
  | ContactInfo
  | Contact
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/lib/sanity.ts
// Variable: getStaffManualQuery
// Query: *[_type == "staff-manual"][0]{title, intro, sections[]->{title, 'label': label->label, content, slug}}
export type GetStaffManualQueryResult = {
  title: string | null;
  intro: string | null;
  sections: Array<{
    title: string | null;
    label: string | null;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    slug: Slug | null;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity.ts
// Variable: getPeopleQuery
// Query: *[_type == "people" && !(_id in path('drafts.**'))]{firstName, lastName, email, projects[] -> {name, "slug":slug.current}, socials, "imageUrl": image.asset->url}
export type GetPeopleQueryResult = Array<{
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  projects: Array<{
    name: string | null;
    slug: string | null;
  }> | null;
  socials: Array<{
    type?: string;
    url?: string;
    _type: 'social';
    _key: string;
  }> | null;
  imageUrl: string | null;
}>;

// Source: ../web/src/lib/sanity.ts
// Variable: getProjectsQuery
// Query: *            [              _type == "project" && !(_id in path('drafts.**'))            ]{              name,                 description,                extraDescription,                 "slug":slug.current,                 "imageUrl": image.asset->url,                 technologies[],                 showOnFrontPage,                 content[] {                  "type":_type,                  "value": select(_type == 'quote' => {text, author}, _type == 'image' => asset->{url, "alt":originalFilename}, _type == 'wideimage' => asset->{url, "alt":originalFilename}, {text}),                }            }
export type GetProjectsQueryResult = Array<{
  name: string | null;
  description: {
    en?: string;
    no?: string;
  } | null;
  extraDescription: string | null;
  slug: string | null;
  imageUrl: string | null;
  technologies: Array<string> | null;
  showOnFrontPage: boolean | null;
  content: Array<
    | {
        type: 'heading';
        value: {
          text: string | null;
        };
      }
    | {
        type: 'image';
        value: {
          url: string | null;
          alt: string | null;
        } | null;
      }
    | {
        type: 'output';
        value: {
          text: string | null;
        };
      }
    | {
        type: 'paragraph';
        value: {
          text: string | null;
        };
      }
    | {
        type: 'quote';
        value: {
          text: string | null;
          author: string | null;
        };
      }
    | {
        type: 'wideimage';
        value: {
          url: string | null;
          alt: string | null;
        } | null;
      }
  > | null;
}>;

// Source: ../web/src/lib/sanity.ts
// Variable: getProjectQuery
// Query: *    [    _type == "project" && slug.current == $projectSlug && !(_id in path('drafts.**'))    ][0]    {      name,       description,       extraDescription,      "slug":slug.current,       "imageUrl": image.asset->url,       technologies[],       showOnFrontPage,       content[] {      "type":_type,      "value": select(_type == 'quote' => {text, author}, _type == 'image' => asset->{url, "alt":originalFilename}, _type == 'wideimage' => asset->{url, "alt":originalFilename}, {text}),    }    }
export type GetProjectQueryResult = {
  name: string | null;
  description: {
    en?: string;
    no?: string;
  } | null;
  extraDescription: string | null;
  slug: string | null;
  imageUrl: string | null;
  technologies: Array<string> | null;
  showOnFrontPage: boolean | null;
  content: Array<
    | {
        type: 'heading';
        value: {
          text: string | null;
        };
      }
    | {
        type: 'image';
        value: {
          url: string | null;
          alt: string | null;
        } | null;
      }
    | {
        type: 'output';
        value: {
          text: string | null;
        };
      }
    | {
        type: 'paragraph';
        value: {
          text: string | null;
        };
      }
    | {
        type: 'quote';
        value: {
          text: string | null;
          author: string | null;
        };
      }
    | {
        type: 'wideimage';
        value: {
          url: string | null;
          alt: string | null;
        } | null;
      }
  > | null;
} | null;

// Source: ../web/src/lib/sanity.ts
// Variable: getJobDescriptionsQuery
// Query: *[_type == "job-description"]{ title, slug, label, subtitle, content}
export type GetJobDescriptionsQueryResult = Array<{
  title: string | null;
  slug: Slug | null;
  label: string | null;
  subtitle: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
}>;

// Source: ../web/src/lib/sanity.ts
// Variable: getJobDescriptionBySlugQuery
// Query: *[_type == "job-description" && slug.current == $slug][0]{ title, slug, label, subtitle, content}
export type GetJobDescriptionBySlugQueryResult = {
  title: string | null;
  slug: Slug | null;
  label: string | null;
  subtitle: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity.ts
// Variable: getPageQuery
// Query: *[_type == "page" && title == $title][0]
export type GetPageQueryResult = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<
    | ({
        _key: string;
      } & Calculator)
    | ({
        _key: string;
      } & CallToAction)
    | ({
        _key: string;
      } & Contact)
    | ({
        _key: string;
      } & Container)
    | ({
        _key: string;
      } & Hero)
    | ({
        _key: string;
      } & Illustration)
    | ({
        _key: string;
      } & ListSection)
    | ({
        _key: string;
      } & Paragraph)
    | ({
        _key: string;
      } & TextSection)
  >;
} | null;

// Source: ../web/src/lib/sanity.ts
// Variable: getCareerValuesQuery
// Query: *[_type == "career-values"][0]
export type GetCareerValuesQueryResult = null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "staff-manual"][0]{title, intro, sections[]->{title, \'label\': label->label, content, slug}}': GetStaffManualQueryResult;
    '*[_type == "people" && !(_id in path(\'drafts.**\'))]{firstName, lastName, email, projects[] -> {name, "slug":slug.current}, socials, "imageUrl": image.asset->url}': GetPeopleQueryResult;
    '*\n            [\n              _type == "project" && !(_id in path(\'drafts.**\'))\n            ]{\n              name, \n                description,\n                extraDescription, \n                "slug":slug.current, \n                "imageUrl": image.asset->url, \n                technologies[], \n                showOnFrontPage, \n                content[] {\n                  "type":_type,\n                  "value": select(_type == \'quote\' => {text, author}, _type == \'image\' => asset->{url, "alt":originalFilename}, _type == \'wideimage\' => asset->{url, "alt":originalFilename}, {text}),\n                }\n            }': GetProjectsQueryResult;
    '*\n    [\n    _type == "project" && slug.current == $projectSlug && !(_id in path(\'drafts.**\'))\n    ][0]\n    {\n      name, \n      description, \n      extraDescription,\n      "slug":slug.current, \n      "imageUrl": image.asset->url, \n      technologies[], \n      showOnFrontPage, \n      content[] {\n      "type":_type,\n      "value": select(_type == \'quote\' => {text, author}, _type == \'image\' => asset->{url, "alt":originalFilename}, _type == \'wideimage\' => asset->{url, "alt":originalFilename}, {text}),\n    }\n    }': GetProjectQueryResult;
    '*[_type == "job-description"]{ title, slug, label, subtitle, content}': GetJobDescriptionsQueryResult;
    '*[_type == "job-description" && slug.current == $slug][0]{ title, slug, label, subtitle, content}': GetJobDescriptionBySlugQueryResult;
    '*[_type == "page" && title == $title][0]': GetPageQueryResult;
    '*[_type == "career-values"][0]': GetCareerValuesQueryResult;
  }
}
