export const logos = [
    { alt: 'aize logo', src: '/logos/aize.svg' },
    { alt: 'avinor logo', src: '/logos/avinor.png' },
    { alt: 'bitfix logo', src: '/logos/bitfix.png' },
    { alt: 'bn logo', src: '/logos/bn.png' },
    { alt: 'dnb logo', src: '/logos/dnb.png' },
    { alt: 'elporten logo', src: '/logos/elporten.png' },
    { alt: 'fremtind logo', src: '/logos/fremtind.png' },
    { alt: 'gintel logo', src: '/logos/gintel.svg' },
    { alt: 'equinor logo', src: '/logos/equinor-logo.png' },
    { alt: 'inatur logo', src: '/logos/inatur.svg' },
    { alt: 'kilter logo', src: '/logos/kilter.png' },
    { alt: 'klp logo', src: '/logos/klp.png' },
    { alt: 'kongsberg logo', src: '/logos/kongsberg.png' },
    { alt: 'lilbit logo', src: '/logos/lilbit2.webp' },
    { alt: 'moller logo', src: '/logos/moller.png' },
    // { alt: 'nomono logo', src: '/logos/nomono.webp' }, TODO add nomono logo with transparent bg
    { alt: 'obos logo', src: '/logos/obos.png' },
    { alt: 'remarkable logo', src: '/logos/remarkable.png' },
    { alt: 'ruter logo', src: '/logos/ruter.png' },
    { alt: 'statkraft logo', src: '/logos/statkraft.png' },
    { alt: 'technipFMC logo', src: '/logos/technip.png' },
    { alt: 'thales logo', src: '/logos/thales.png' },
    { alt: 'thomas Reuters logo', src: '/logos/thomson.png' }
  ];